language: java
sudo: false

services:
- docker

git:
  depth: false

env:
  - TANGO_HOST=localhost:10000

#skip mvn install
install: /bin/true

before_script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps
script:
  - mvn clean install -Ptravis
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'


jobs:
  include:
    - stage: deploy
      name: "Deploy to SonarCloud"
      jdk: openjdk8
      script:
        - mvn clean install -Ptravis
        - mvn sonar:sonar -Ptravis
      addons:
        sonarcloud:
          organization: "tango-controls"
          token:
            secure: $SONAR_TOKEN
    -
      name: "Deploy to Codacy"
      jdk: openjdk8
      script:
        - mvn clean install -Ptravis
        - mvn com.gavinmogan:codacy-maven-plugin:coverage -Ptravis
    -
      name: "Deploy to Codcov.io"
      jdk: openjdk8
      script:
        - mvn clean install -Ptravis
        - bash <(curl -s https://codecov.io/bash)
    -
      name: "Deploy artifacts"
      jdk: openjdk8
      before_script: true #override before_script
      script:
        - cd parent
        - mvn versions:set versions:update-child-modules -DnewVersion=${TRAVIS_BRANCH} -DprocessAllModule -DgenerateBackupPoms=false
        - cd ..
        - mvn install -Dmaven.test.skip=true
      deploy:
        - provider: script
          script: bash .travis/maven_deploy.sh
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          file: assembly/target/JTango-${TRAVIS_TAG}.jar
          api_key: $GITHUB_TOKEN
          skip_cleanup: true
          draft: true
          on:
            tags: true
